services:
  mongo1:
    image: mongo:4.4
    container_name: mongo1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/secrets/mongo-keyfile"]
    volumes:
      - ./data/mongo1:/data/db
      - ./secrets/mongo-keyfile:/etc/secrets/mongo-keyfile:ro
    networks:
      mongo-cluster:
        aliases:
          - mongo1

  mongo2:
    image: mongo:4.4
    container_name: mongo2
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/secrets/mongo-keyfile"]
    volumes:
      - ./data/mongo2:/data/db
      - ./secrets/mongo-keyfile:/etc/secrets/mongo-keyfile:ro
    networks:
      mongo-cluster:
        aliases:
          - mongo2

  mongo3:
    image: mongo:4.4
    container_name: mongo3
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/secrets/mongo-keyfile"]
    volumes:
      - ./data/mongo3:/data/db
      - ./secrets/mongo-keyfile:/etc/secrets/mongo-keyfile:ro
    networks:
      mongo-cluster:
        aliases:
          - mongo3

networks:
  mongo-cluster:
    driver: bridge